version: '3.8'

services:
  crm:
    image: crm:latest
    build: ./web-customer-tracker-noxml-security
    ports:
      - 8080:8080
    depends_on:
      - postgres-data
      - postgres-login
    environment:
      - JDBC_URL=jdbc:postgresql://postgres-data:5432/web_customer_tracker
      - SECURITY_JDBC_URL=jdbc:postgresql://postgres-login:5432/spring_security_bcrypt

  postgres-data:
    image: 'postgres:14-alpine'
    volumes:
      - ./sql-data:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web_customer_tracker
      
  postgres-login:
    image: 'postgres:14-alpine'
    volumes:
      - ./sql-login:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring_security_bcrypt